services:

  sqlexpress:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlexpress
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
    - "14330:1433"  # Porta externa 14330, interna continua 1433
    networks:
      - mednet
    volumes:
      - sql_data:/var/opt/mssql  # Adiciona o volume para persistência de dados

  hackathon-auth-service:
    build: ./Hackathon.AuthService
    container_name: hackathon-auth-service
    ports:
      - "5001:8080"
    depends_on:
      - sqlexpress
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - dataprotection-keys:/root/.aspnet/DataProtection-Keys 
    networks:
      - mednet

  hackathon-user-service:
    build: ./Hackathon.UserService
    container_name: hackathon-user-service
    ports:
      - "5002:8080"
    depends_on:
      - sqlexpress
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - dataprotection-keys:/root/.aspnet/DataProtection-Keys 
    networks:
      - mednet

  hackathon-schedule-service:
    build: ./Hackathon.ScheduleService
    container_name: hackathon-schedule-service
    ports:
      - "5003:8080"
    depends_on:
      - sqlexpress
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - dataprotection-keys:/root/.aspnet/DataProtection-Keys 
    networks:
      - mednet

  hackathon-consultation-service:
    build: ./Hackathon.ConsultationService
    container_name: hackathon-consultation-service
    ports:
      - "5004:8080"
    depends_on:
      - sqlexpress
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
          - dataprotection-keys:/root/.aspnet/DataProtection-Keys 
    networks:
      - mednet

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - mednet

networks:
  mednet:
    name: hackatonfiap5nett_mednet
    driver: bridge

volumes:
  sql_data:
  dataprotection-keys:  # Volume para persistir as chaves de proteção de dados