global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'auth-service'
    static_configs:
      - targets: ['hackathon-auth-service:80']

  - job_name: 'user-service'
    static_configs:
      - targets: ['hackathon-user-service:80']

  - job_name: 'schedule-service'
    static_configs:
      - targets: ['hackathon-schedule-service:80']

  - job_name: 'consultation-service'
    static_configs:
      - targets: ['hackathon-consultation-service:80']
