apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: dataprotection-keys
  name: dataprotection-keys
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
